[package]
name = "cuckoo-rs"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
quickcheck = "1.0.3"
quickcheck_macros = "1.0.0"
criterion = "0.5.1"
rand = "0.8.5"

[[bench]]
name = "cuckoo_hash_benchmark"
harness = false